#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorAlpha,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBeta,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorGamma,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorDelta,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoAlpha,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoBeta,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servoGamma,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servoDelta,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servoEpsilon,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servoZeta,            tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Copyright 2014 FTC Team 7553 - Thavma
//By Richard. Fixes by Alex.

#include "JoystickDriver.c"

void drive()
{
	motor[motorAlpha] = joystick.joy1_y1;
	motor[motorGamma] = -joystick.joy1_y2;
}

void chinup()
{
	if(joy2Btn(1) == 1) {
		motor[motorBeta] = 100;
		wait1Msec(100);
		motor[motorBeta] = 0;
	}

	if(joy2Btn(4) == 1) {
		motor[motorBeta] = -100;
		wait1Msec(100);
		motor[motorBeta] = 0;
	}
}

void twang()
{
    if(joy1Btn(1) == 1) {
    	servo[servoAlpha] = ServoValue[servoAlpha] + 5;
    	wait1Msec(100);
    	servo[servoAlpha] = ServoValue[servoAlpha];
    }

    if(joy1Btn(2) == 1) {
    	servo[servoAlpha] = ServoValue[servoAlpha] - 5;
    	wait1Msec(100);
    	servo[servoAlpha] = ServoValue[servoAlpha];
	}
}

void flag()
{
	if(joy2Btn(3) == 1) {
		motor[motorDelta] = 100;
		wait1Msec(100);
		motor[motorDelta] = 0;
	}

	if(joy2Btn(2) == 1) {
		motor[motorDelta] = -100;
		wait1Msec(100);
		motor[motorDelta] = 0;
	}

}

task main()
{

	getJoystickSettings(joystick);

	while(true)
	{
		drive();

		chinup();

		twang();

		flag();
	}
}
